name: pytorch_docs_search
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0.1
  - openai=1.2.4
  - numpy=1.26.4  # Downgrade to pre-NumPy 2.0 for compatibility
  - tqdm=4.66.1
  - python-dotenv=1.0.0
  - psutil=5.9.0
  - pytest=7.4.3
  - black=23.11.0
  - werkzeug=2.2.3  # Add specific Werkzeug version compatible with Flask
  - flask=2.2.3
  - pip:
    - chromadb==0.4.18  # Move to pip to ensure compatibility
    - tree-sitter==0.20.1
    - tree-sitter-languages==1.7.0